<a href="https://colab.research.google.com/github/Akhileshkumarsingh21221/ML-Lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
#creating empty array

empty_array= np.array([])
empty_array

array([], dtype=float64)

In [17]:
# creating 2d array

two_d_array1=np.array([[1,2,3],[4,5,6],[7.,8,9]])
two_d_array1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [34]:
# 25 random number geeneration

random_25_num=np.random.rand(25)
print(random_25_num)
print('\n')
random_25_num_int=np.random.randint(25)
print(random_25_num_int)

[0.94187901 0.29265751 0.91615732 0.62602236 0.57083448 0.30601706
 0.46714669 0.74611432 0.23917481 0.76336817 0.85230608 0.33026976
 0.45674013 0.12121582 0.09267017 0.74418269 0.69539096 0.9490564
 0.84860918 0.28376426 0.67674859 0.95667901 0.99023224 0.15728775
 0.45721919]


24


In [19]:
# Find Dot product of two arrays
two_d_array2=np.array([[11,12,13],[14,15,16],[17,18,19]])

dot_product=np.dot(two_d_array1,two_d_array2.T)
dot_product


array([[ 74.,  92., 110.],
       [182., 227., 272.],
       [290., 362., 434.]])

In [21]:
array3=np.array([[3, 7, 1],
[10, 3, 2],
[5, 6, 7]
])

In [22]:
array3

array([[ 3,  7,  1],
       [10,  3,  2],
       [ 5,  6,  7]])

In [23]:
sorted_array3_col=np.sort(array3,axis=0)

In [26]:
sorted_array3_row=np.sort(array3,axis=1)
sorted_array3_row

array([[ 1,  3,  7],
       [ 2,  3, 10],
       [ 5,  6,  7]])

In [28]:
sorted_as_wholearray3=np.sort(array3)
sorted_as_wholearray3

array([[ 1,  3,  7],
       [ 2,  3, 10],
       [ 5,  6,  7]])

In [29]:
list1=np.array([1,2,3,4])
list2=np.array([1,2,3,4])
list3=np.array([1,2,3,4])

In [31]:
print(list1)
print(list2)
print(list3)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [41]:
avg1=np.average(list1)

In [37]:
avg1

2.5

In [43]:
# Make a list of 3 numpy arrays and find the mean of all the numpy arrays and output them as a list

list1=np.array([1,2,3,4])
list2=np.array([1,2,3,4])
list3=np.array([1,2,3,4])
print(list1)
print(list2)
print(list3)
avg1=np.average(list1)
avg2=np.average(list2)
avg3=np.average(list3)
avg=[avg1,avg2,avg3]
print(avg)


[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[2.5, 2.5, 2.5]


In [44]:
# Make a numpy array containing the string 'PHP C# Python C Java C++' as the only element, then split it on the basis of spaces.

arr=np.array(["PHP C# Python C Java C++"])
print(arr)
arr1=np.array(arr[0].split())
print(arr1)


['PHP C# Python C Java C++']
['PHP' 'C#' 'Python' 'C' 'Java' 'C++']
